#!/usr/bin/env bash
# handles redirection

sudo apt-get -y install nginx
sudo bash -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
redirect="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.google.com;\n\t}\n"
sudo sed -i "53s|.*|$redirect|" /etc/nginx/sites-enabled/default
sudo service nginx restart
