#!/usr/bin/env bash
# Update the package list and install HAProxy

sudo apt-get -y update
sudo apt-get -y install haproxy
echo "frontend http
	bind *:80
	mode http
	default_backend web_backend
    backend web_backend
    	balance roundrobin
	server 267917-web-01 34.202.233.229:80 check
	server 267917-web-02 100.27.0.17:80 check " >> /etc/haproxy/haproxy.cfg

service haproxy restart
